plugins {
    id "base"
    id "fabric-loom" version "${loom_version}" apply false
}

allprojects {
    group = "io.github.melswg.worldmind"
    version = project.mod_version

    repositories {
        mavenCentral()
    }
}

subprojects {
    plugins.withId("java") {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(17)
            }
        }

        tasks.withType(JavaCompile).configureEach {
            options.release = 17
            options.encoding = "UTF-8"
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }

    tasks.withType(Jar).configureEach {
        from(rootProject.layout.projectDirectory.file("LICENSE")) {
            into("META-INF")
            rename { "LICENSE-worldmind" }
        }
    }
}
