plugins {
    id "java-library"
}

dependencies {
    api project(":core")
    implementation "org.xerial:sqlite-jdbc:3.53.1.0"

    testImplementation platform("org.junit:junit-bom:5.10.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}
